#!/usr/bin/env bash

. scripts/env.sh

mkdir -p $TOP/out/build/weston
cd $TOP/out/build/weston
mkdir -p m4
$TOP/weston/autogen.sh --host=${CROSS_COMPILE%"-"} --prefix=$PREFIX --with-sysroot=$SYSROOT --disable-x11-compositor --disable-rpi-compositor --enable-demo-clients-install
make -j$NPROC && fakeroot make DESTDIR=$SYSROOT install
# Fix permissions of weston-launch which was installed using fakeroot
sudo chown root $SYSROOT/$PREFIX/bin/weston-launch
sudo chmod u+s $SYSROOT/$PREFIX/bin/weston-launch
