#!/usr/bin/env bash

set -e

PACKAGE=weston

. scripts/env.sh

cd_package

mkdir -p m4
run_autogen \
--disable-x11-compositor \
--disable-rpi-compositor \
--enable-demo-clients-install

run_make
# Use fakeroot since a weston-launch is attempted to be root suid
fakeroot make DESTDIR=$SYSROOT install
# Fix permissions of weston-launch which was installed using fakeroot
sudo chown root $SYSROOT/$NV_PREFIX/bin/weston-launch
sudo chmod u+s $SYSROOT/$NV_PREFIX/bin/weston-launch

package_success
