#!/usr/bin/env bash

set -e

PACKAGE=xserver

. scripts/env.sh

cd_package

run_autogen \
--enable-glamor

run_make
run_make install

# also install xkeyboard-config, xkbcomp and xf86-input-evdev packages

package_success
