#!/usr/bin/env bash

set -e

PACKAGE=drm

. scripts/env.sh

cd_package

run_autogen \
--enable-tegra-experimental-api \
--disable-cairo-tests \
--disable-intel \
--disable-radeon \
--disable-vmwgfx

run_make
run_make install

package_success
