#!/usr/bin/env bash

. scripts/env.sh

mkdir -p $TOP/out/build/wayland
cd $TOP/out/build/wayland
$TOP/wayland/autogen.sh --host=${CROSS_COMPILE%"-"} --prefix=$PREFIX --disable-documentation
make -j4 && make install
