#!/usr/bin/env bash

set -e

PACKAGE=linux

. scripts/env.sh

cd_package

make -j$NPROC -C $TOP/linux ARCH=arm O=$PWD CROSS_COMPILE=$CROSS_COMPILE tegra_defconfig dtbs zImage modules
sudo cp $TOP/out/build/linux/arch/arm/boot/zImage $SYSROOT/boot
sudo cp $TOP/out/build/linux/arch/arm/boot/dts/tegra124-* $SYSROOT/boot
sudo make -C $TOP/linux ARCH=arm O=$PWD CROSS_COMPILE=$CROSS_COMPILE INSTALL_MOD_PATH=$SYSROOT modules_install

package_success
