#!/usr/bin/env bash

set -e

PACKAGE=linux

. scripts/env.sh

cd_package

run_make_kernel()
{
    make -C $TOP/linux ARCH=arm O=$PWD CROSS_COMPILE=$CROSS_COMPILE INSTALL_MOD_PATH=$SYSROOT $*
}

# Create config is none exists yet
if [ ! -f $TOP/out/build/$DISTRO/linux/.config ]; then
    run_make_kernel tegra_defconfig
fi

# Build all that we need
run_make_kernel -j$NPROC oldconfig dtbs zImage modules

# Install zImage
cp $TOP/out/build/$DISTRO/linux/arch/arm/boot/zImage $SYSROOT/boot/zImage-nouveau

# Install dtbs
mkdir -p $SYSROOT/boot/dtb-nouveau
cp $TOP/out/build/$DISTRO/linux/arch/arm/boot/dts/tegra124-* $SYSROOT/boot/dtb-nouveau

# Install modules
run_make_kernel modules_install
# Remove nouveau modules (we want to use the ones from the nouveau repository)
KREL=$(run_make_kernel -s kernelrelease)
rm -Rf $SYSROOT/lib/modules/$KREL/kernel/drivers/gpu/drm/nouveau

# Generate boot script
$TOP/tegra-uboot-scripts/gen-uboot-script.py --zimage zImage-nouveau --dtb-dir /boot/dtb-nouveau --cmdline "nouveau.pstate=1 text" -o $SYSROOT/boot/boot-nouveau.scr
ln -sfr $SYSROOT/boot/boot-nouveau.scr $SYSROOT/boot/boot.scr

package_success
