#!/usr/bin/env bash

set -e

PACKAGE=wayland

. scripts/env.sh

cd_package

$TOP/wayland/autogen.sh --host=${CROSS_COMPILE%"-"} --prefix=$PREFIX --with-sysroot=$SYSROOT \
--disable-documentation \
--disable-scanner

make -j$NPROC
make DESTDIR=$SYSROOT install

package_success
