#!/usr/bin/env bash

if [[ -z "$TOP" ]]; then
    echo "Error: TOP env var not set."
    exit 1
fi

if [[ -z "$CROSS_COMPILE" ]]; then
    echo "Error: CROSS_COMPILE env var not set."
    exit 1
fi

cd $TOP/mesa
./autogen.sh --host=${CROSS_COMPILE%"-"} --prefix=$TOP/out/root/home/ubuntu/usr --without-dri-drivers --with-gallium-drivers=nouveau --enable-gallium-egl --enable-gbm --enable-egl --with-egl-platforms=drm,wayland --enable-gles1 --enable-gles2 --enable-opengl
make -j4
sudo make install
