#!/usr/bin/env bash

set -e

PACKAGE=mesa

. scripts/env.sh

cd_package

run_autogen \
--without-dri-drivers \
--with-gallium-drivers=nouveau,tegra \
--enable-gbm \
--enable-egl \
--with-egl-platforms=drm,x11,wayland \
--enable-gles1 \
--enable-gles2 \
--enable-opengl \
--enable-osmesa \
--enable-shared-glapi \
--enable-dri3 \
--enable-glx \
--enable-glx-tls \
--enable-texture-float

run_make
run_make install

package_success
