#!/usr/bin/env bash

set -e

PACKAGE=pthread-stubs

. scripts/env.sh

cd_package

run_autogen --host=${CROSS_COMPILE%"-"} --prefix=$PREFIX --with-sysroot=$SYSROOT

make -j$NPROC
make install

package_success
