#!/usr/bin/env bash

set -e

. scripts/env.sh

f=$LINARO_GCC_PACKAGE.tar.xz
mkdir -p $TOP/out
outfile=$TOP/out/$f
url="https://releases.linaro.org/${LINARO_GCC_RELEASE}/components/toolchain/binaries/$f"

if [ ! -e "$TOP/$LINARO_GCC_PACKAGE" ]; then
    if [ ! -f "$outfile" ]; then
        status "Downloading $url..."
        wget $url -O $outfile || { rm $outfile; exit 1; }
    fi
    status "Extracting..."
    mkdir -p $TOP
    tar xJf $outfile -C $TOP
    rm $outfile
fi

# Now cross compile a few tools that we will need locally...
unset CFLAGS CXXFLAGS CROSS_COMPILE SYSROOT PKG_CONFIG_DIR PKG_CONFIG_LIBDIR PKG_CONFIG_SYSROOT_DIR PKG_CONFIG_PATH PKG_CONFIG

# pkg-config
PKG_CONFIG_VERSION=0.28
outfile=$TOP/out/pkg-config-$PKG_CONFIG_VERSION.tar.gz
url=http://pkgconfig.freedesktop.org/releases/pkg-config-$PKG_CONFIG_VERSION.tar.gz
if [ ! -f "$outfile" ]; then
    status "Downloading $url"
    wget $url -O $outfile || { rm $outfile; exit 1; }
fi

if [ ! -e "$TOP/pkg-config-$PKG_CONFIG_VERSION" ]; then
    tar xfz $outfile -C $TOP
fi

if [ ! -f "$TOP/$LINARO_GCC_PACKAGE/bin/pkg-config" ]; then
    cd $TOP/pkg-config-$PKG_CONFIG_VERSION
    ./configure && make
    cp $TOP/pkg-config-$PKG_CONFIG_VERSION/pkg-config $TOP/$LINARO_GCC_PACKAGE/bin
fi

# wayland-scanner
if [ ! -f "$TOP/$LINARO_GCC_PACKAGE/bin/wayland-scanner" ]; then
    mkdir -p $TOP/out/build/wayland-scanner
    cd $TOP/out/build/wayland-scanner
    $TOP/wayland/autogen.sh --disable-documentation
    make wayland-scanner
    cp wayland-scanner $TOP/$LINARO_GCC_PACKAGE/bin
fi

status "Cross-compilation toolchain successfully downloaded"
