#!/usr/bin/env bash

if [[ -z "$TOP" ]]; then
    echo "Error: TOP env var not set."
    exit 1
fi

f=Tegra_Linux_Sample-Root-Filesystem_R19.3.0_armhf.tbz2
mkdir -p $TOP/out
outfile=$TOP/out/$f
root=$TOP/out/root
echo "Downloading rootfs..."
curl https://developer.nvidia.com/sites/default/files/akamai/mobile/files/L4T/$f -o $outfile

if [ -d "$root" ]; then
    read -p "$root will be overwritten. Continue (y/n)? " choice
    case "$choice" in 
          y|Y ) ;;
          n|N ) exit 1;;
          * ) exit 1;;
    esac
    echo "Removing existing rootfs..."
    sudo rm -rf $root
fi
echo "Extracting rootfs..."
mkdir -p $root
sudo tar xpf $outfile -C $root
