#!/usr/bin/env bash

set -e

. scripts/env.sh

f=Tegra_Linux_Sample-Root-Filesystem_R19.3.0_armhf.tbz2
mkdir -p $TOP/out
outfile=$TOP/out/$f
root=$SYSROOT

if [ ! -f "$outfile" ]; then
    status "Downloading rootfs..."
    curl https://developer.nvidia.com/sites/default/files/akamai/mobile/files/L4T/$f -o $outfile
fi

# Do not overwrite or remove existing rootfs. The user might have copied or linked an already existing rootfs there.
if [ ! -e "$root" ]; then
    status "Extracting rootfs..."
    mkdir -p $root
    sudo tar xpf $outfile -C $root
fi

f=Tegra124_Linux_R19.3.0_armhf.tbz2
outfile=$TOP/out/$f
root=$TOP/out/Linux_for_Tegra

if [ ! -f "$outfile" ]; then
    status "Downloading binary drivers..."
    curl https://developer.nvidia.com/sites/default/files/akamai/mobile/files/L4T/$f -o $outfile
fi

if [ ! -e "$root" ]; then
    status "Extracting binary drivers..."
    cd $TOP/out
    sudo tar xpf $outfile
fi

cd $root
status "Installing binary drivers..."
sudo ./apply_binaries.sh --root $SYSROOT
status "L4T rootfs successfully downloaded into $SYSROOT!"