#!/usr/bin/env bash

set -e

. scripts/env.sh

f=$LINARO_GCC_PACKAGE.tar.xz
mkdir -p $TOP/out
outfile=$TOP/out/$f
url="https://releases.linaro.org/${LINARO_GCC_RELEASE}/components/toolchain/binaries/$f"
if [ ! -f "$outfile" ]; then
    status "Downloading $url..."
    wget $url -O $outfile
fi

if [ ! -e "$TOP/$LINARO_GCC_PACKAGE" ]; then
    status "Extracting..."
    mkdir -p $TOP
    tar xJf $outfile -C $TOP
    rm $outfile
fi

status "Cross-compilation toolchain successfully downloaded"
