#!/usr/bin/env bash

if [[ -z "$TOP" ]]; then
    echo "Error: TOP env var not set."
    exit 1
fi

if [[ -z "$CROSS_COMPILE" ]]; then
    echo "Error: CROSS_COMPILE env var not set."
    exit 1
fi

if [[ -z "$BOARD_ROOT" ]]; then
    echo "Error: BOARD_ROOT env var not set."
    exit 1
fi

if ! mountpoint -q $BOARD_ROOT; then
    echo "Error: $BOARD_ROOT not mounted."
    exit 1
fi

sudo make -C $TOP/linux ARCH=arm O=$TOP/out/linux M=$TOP/nouveau/drm CROSS_COMPILE=$CROSS_COMPILE INSTALL_MOD_PATH=$BOARD_ROOT modules_install
