#!/usr/bin/env bash

if [[ -z "$TOP" ]]; then
    echo "Error: TOP env var not set."
    exit 1
fi

if [[ -z "$BOARD_ROOT" ]]; then
    echo "Error: BOARD_ROOT env var not set."
    exit 1
fi

if ! mountpoint -q $BOARD_ROOT; then
    echo "Error: $BOARD_ROOT not mounted."
    exit 1
fi

sudo mkdir -p $BOARD_ROOT/lib/firmware/nouveau
sudo cp $TOP/firmware/* $BOARD_ROOT/lib/firmware/nouveau
